planning_nodelet:
  main_freq: 3
  wall_frame: "wall"
  robot_frame: "base_link"

  # Model parameters
  nbr_int_steps: 10  # initial number of integration steps
  model_constants: [0, 17.68e-3, -6.0e-1, 29.74e-8, -0.4, -4.1, -0.19, 0.22,
                    -1.51, -1.3, 0.21, -0.4, 2.0]
  max_lat_rudder: 15   # maximum angle of the lateral rudder
  max_elev_rudder: 10  # maximum angle of the elevation rudder

  # Planning parameters
  plan_speed: 3.0     # planned speed (m/s) of the robot
  plan_horizon: 1.5   # horizon (m) of the planning
  lattice_res: 0.4    # resolution (m) of the waypoints lattice
  min_wall_dist: 0.2  # minimum distance to the wall that can be planned

  camera_height: 5    # number of pixels of the camera along height (-1 for actual camera size)
  camera_width: 10    # number of pixels of the camera along width  (-1 for actual camera size)
