robot_simulator:
  update_freq: 10.0
  fixed_frame: "ocean"
  robot_frame: "base_link"

  # Robot dimensions
  robot_length: 1.0
  robot_width: 0.3

  # Model parameters
  nbr_int_steps: 10  # initial number of integration steps
  model_constants: [0, 17.68e-3, -6.0e-1, 29.74e-8, -0.4, -4.1, -0.19, 0.22,
                    -1.51, -1.3, 0.21, -0.4, 2.0]
  init_state: [1, 0, 3,  # x, y, z (position)
               0, 0, -1.5707963,  # phi, theta, psi (orientation)
               0, 0, 0,  # u, v, w (linear speed)
               0, 0, 0,  # p, q, r (angular speed)
               0.0]      # delta_m (ballast)

  # Bounds on the state and the input
  bnd_delta_m: 0.02
  bnd_input: [4300, 15, 10, 0.01]
