gp_nodelet:
  main_freq: 5.0
  wall_frame: "wall"

  # Sensor model
  camera_var: 0.2     # max variance on camera measurements
  camera_decay: 0.5   # exponential decay rate (m) on camera measurements

  # Gaussian Process behaviour
  matern_length: 0.2  # lengthscale of the Matern kernel
  matern_var: 1.2     # signal variance of the Matern kernel
  gp_init_mean: 1.0   # initial mean values of the Gaussian Process
  gp_noise_var: 0.2   # noise variance of the Gaussian Process

  # Dimensions
  size_wall_x: 2.0    # size (m) of the algae wall in the x direction
  size_wall_y: 10.0   # size (m) of the algae wall in the y direction
  size_gp_x: 10        # size of the Gaussian Process mean in the x direction
  size_gp_y: 50       # size of the Gaussian Process mean in the y direction
  size_img_x: 20      # size of the output image in the x direction
  size_img_y: 100     # size of the output image in the y direction
  batch_size: 1000      # batch size for the Kalman update of the GP
