planning_nodelet:
  main_freq: 1.0
  ocean_frame: "ocean"
  wall_frame: "wall"
  robot_frame: "base_link"
  camera_frame: "camera"

  horiz_motion: false  # whether to allow motion in the horizontal plane
  vert_motion: true    # whether to allow motion in the vertical plane
  plan_speed: 1.5      # planned speed (m/s) of the robot
  plan_horizon: 1.5    # horizon (m) of the planning
  plan_res: 0.1        # spatial resolution (m) of the planned trajectory
  lattice_res: 0.4     # resolution (m) of the waypoints lattice
  min_wall_dist: 0.2   # minimum distance to the wall that can be planned
  gp_weight: 100       # weight attributed to the Gaussian Process values in viewpoint selection

  camera_height: 5  # number of pixels of the camera along height (-1 for actual camera size)
  camera_width: 10  # number of pixels of the camera along width  (-1 for actual camera size)


cart_control_nodelet:
  main_freq: 10
  speed: 0.2  # desired robot speed


mpc_nodelet:
  main_freq: 10

  nominal_speed: 1.5  # nominal speed (m/s) of the robot
  time_horizon: 2.0   # time horizon (s) for the MPC prediction
  nbr_steps: 10       # number of steps for the MPC prediction (fixed in CVXGEN)
