planning_nodelet:
  main_freq: 0.2
  ocean_frame: "ocean"
  wall_frame: "wall"
  robot_frame: "base_link"
  camera_frame: "camera"

  # Lattice of viewpoint generation
  horiz_motion: true     # whether to allow motion in the horizontal plane
  vert_motion: true      # whether to allow motion in the vertical plane
  mult_lattices: true    # whether to use multi-lattices planning
  nbr_lattices: 5        # number of lattices for multi-lattices planning
  cart_lattice: false    # whether to create a cartesian lattice, or use motion model instead
  plan_speed: 0.5        # planned speed (m/s) of the robot
  plan_horizon: 1.0      # horizon (m) of the planning (for each lattice)
  lattice_size_horiz: 4  # size of the lattice in the horizontal direction (half size when single-lattice planning)
  lattice_size_vert: 4   # size of the lattice in the vertical direction (half size when single-lattice planning)
  wall_orientation: 1.5707963  # orientation of the algae wall (absolute value)
  lattice_res: 0.4       # resolution (m) of the waypoints lattice (for cartesian lattice)
  bnd_wall_dist: [0.5, 1.5]  # bounds on the distance to the wall for waypoint selection
  bnd_depth: [0.2, 1.8]      # bounds on the depth (in wall frame) for waypoint selection
  bnd_pitch: 60.0            # bound on pitch angle (in degree)

  # Viewpoint selection
  camera_height: -1  # number of pixels of the camera along height (-1 for actual camera size)
  camera_width:  -1  # number of pixels of the camera along width  (-1 for actual camera size)
  gp_weight: 100     # weight attributed to the Gaussian Process values in viewpoint selection

  # Path generation
  linear_path: false     # whether to create a linear path, or a spline one
  plan_res: 0.1          # spatial resolution (m) of the planned trajectory


planning_logic:
  main_freq: 5.0
  path_frame: 'ocean'               # frame in which the transition path is expressed
  wp_file_name: 'resources/wp.txt'  # path to the file containing the transition waypoints
  transition_file_name: 'resources/transition.txt'  # path to the file containing the points delimiting the transitions
  plan_res: 0.1                     # spatial resolution (m) of the transition path


cart_control_nodelet:
  main_freq: 10
  speed: 0.2  # desired robot speed


mpc_node:
  main_freq: 50
  fixed_frame: "ocean"

  desired_speed: 0.5  # desired speed (m/s) of the robot
  time_horizon: 1.5   # time horizon (s) for the MPC prediction
  nbr_steps: 10       # number of steps for the MPC prediction
  disable_vbs: false  # whether to disable the Variable Buoyancy System (VBS)
  ltv_mpc: true       # whether to use the Linear Time Varying (LTV) version of MPC

  P: [10000.0, 10000.0, 10000.0,
      0.01, 0.01, 0.01,
      0.001, 0.001, 0.001,
      0.001, 0.001, 0.001,
      1.0]  # diagonal of the penalty on the last state error
  Q_x: [10000.0, 10000.0, 10000.0,
        0.0, 0.0, 0.0,
        0.1, 0.1, 0.1,
        0.1, 0.1, 0.1,
        0.1]  # diagonal of the penalty on the intermediary states error
  R_u: [0.001, 0.001, 0.001, 100000.0]      # diagonal of the penalty on the control input error
  R_delta: [0.0, 0.0, 0.0, 0.0]  # diagonal of the penalty on the control change rate
